---
# Local group variables for Arch Linux setup
basic_pkgs:
  - openssh
  - vim
  - htop
  - tree
  - unzip
  - neofetch
  - nmap
  - dnsutils
  - gnupg
  - openssl

kde_packages:
  - plasma-meta
  - kde-system-meta
  - konsole
  - kate
  - markdownpart
  - kbackup
  - kcalc
  - kcharselect
  - kclock
  - kdebugsettings
  - kdf
  - kgpg
  - krunner
  - sweeper
  - okular
  - colord-kde
  - kcolorchooser
  - kdegraphics-thumbnailers
  - kgraphviewer
  - svgpart
  - kget
  - kleopatra

aur_packages:
  - brave-bin
  - libreoffice-still

lazyvim_deps:
  - lua
  - luarocks
  - fd
  - fzf
  - unzip
  - tectonic
