- name: Bootstrap development environment
  hosts: localhost

  tasks:
    - name: Install zsh
      community.general.pacman:
      name: zsh
      state: present

    - name: Make zsh standard shell
      ansible.builtin.systemd:
        name: sddm
        state: started
        enabled: true

    - name: Install starship
      community.general.pacman:
      name: nerd-fonts, starship
      state: present

    - name: Copy Starship configuration
      ansible.builtin.template:
        src: /mytemplates/foo.j2
        dest: ~/.config/starship.toml
        owner: USER
        group: USER
        mode: '0644'

    - name: Setup starship in .zshrc
        # append eval "$(starship init zsh)" to .zshc
