- name: Post Arch Linux setup for VMware Setup
  hosts: local
  gather_facts: yes
  roles:
    - role: pacman-update
    - role: basic-pkgs
    - role: vmware-tools
    - role: firewall
    - role: graphics
    - role: kde-plasma
    - role: zsh
    - role: dev-tools
    - role: docker
    - role: aur-setup
    - role: dotfiles
