- name: Post Arch Linux setup
  hosts: local
  gather_facts: yes
  roles:
    - role: pacman-update
    - role: vmware-tools
    - role: firewall
    - role: graphics
    - role: kde-plasma
    - role: aur-setup
    - role: zsh
    - role: python
    - role: lazyvim
    - role: docker
    - role: convenience-apps
    - role: dotfiles
