---
- name: Install gtkmm3 for copy & paste support
  community.general.pacman:
    name: gtkmm3
    state: present
  become: yes
  tags: vmware

- name: Enable and start vmtoolsd service
  ansible.builtin.systemd:
    name: vmtoolsd.service
    enabled: yes
    state: started
  become: yes
  tags: vmware

- name: Enable and start vmware-vmblock-fuse service
  ansible.builtin.systemd:
    name: vmware-vmblock-fuse.service
    enabled: yes
    state: started
  become: yes
  tags: vmware

# So far best way to fix copy/paste issues between host and guest on VMware
# https://github.com/krisztianfekete/clipway
- name: Install open-vm-tools-clipway (AUR) for bidirectional clipboard sync
  ansible.builtin.command: paru -S --noconfirm open-vm-tools-clipway
  tags: vmware

