---
# .zshrc aliases
- name: Add content to .zshrc from template
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['user_dir'] }}/.zshrc"
    block: "{{ lookup('template', 'templates/.zshrc.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Aliases"
    create: yes
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: dotfiles

- name: Install Robovim
  ansible.builtin.git:
    repo: https://github.com/ironlegit/nvim-config
    dest: "{{ ansible_facts['user_dir'] }}/.config/nvim"
    depth: 1
    update: yes # in case it already exists
  tags: dotfiles
