---
# .zshrc starship
- name: Copy starship configuration
  ansible.builtin.template:
    src: starship.toml.j2
    dest: "{{ ansible_facts['user_dir'] }}/.config/starship.toml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: dotfiles

# .zshrc aliases
- name: Add content to .zshrc from template
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['user_dir'] }}/.zshrc"
    block: "{{ lookup('template', 'templates/.zshrc.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Aliases"
    create: yes
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: dotfiles

# Konsole
- name: Deploy Konsole configuration
  ansible.builtin.template:
    src: konsolerc.j2
    dest: "{{ ansible_facts['user_dir'] }}/.config/konsolerc"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: dotfiles

- name: Ensure ~/.local/share/konsole exists for profile and colorscheme
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.local/share/konsole"
    state: directory
    mode: '0755'
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
  tags: dotfiles
  
- name: Deploy Konsole profile
  ansible.builtin.template:
    src: main_zsh.profile.j2
    dest: "{{ ansible_facts['user_dir'] }}/.local/share/konsole/main_zsh.profile"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: dotfiles

- name: Deploy Konsole coloscheme
  ansible.builtin.template:
    src: Sweet-Ambar-Blue.colorscheme.j2
    dest: "{{ ansible_facts['user_dir'] }}/.local/share/konsole/Sweet-Ambar-Blue.colorscheme"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: dotfiles
