---
# .zshrc starship
- name: Copy starship configuration
  ansible.builtin.template:
    src: starship.toml.j2
    dest: "{{ ansible_facts['user_dir'] }}/.config/starship.toml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: zsh

# .zshrc aliases
- name: Add content to .zshrc from template
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['user_dir'] }}/.zshrc"
    block: "{{ lookup('template', 'templates/.zshrc.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Aliases"
    create: yes
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: zsh

# - name: Append rendered template to .zshrc
#   ansible.builtin.shell: |
#     cat << 'EOF' >> ~/.zshrc
#     {{ lookup('template', 'templates/.zshrc.j2') | indent(4) }}
#     EOF
#   args:
#     executable: /bin/zsh


# Konsole
- name: Deploy Konsole configuration
  ansible.builtin.template:
    src: konsolerc.j2
    dest: "{{ ansible_facts['user_dir'] }}/.config/konsolerc"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'

- name: Deploy Konsole profile
  ansible.builtin.template:
    src: main_zsh.profile.j2
    dest: "{{ ansible_facts['user_dir'] }}/.local/share/konsole/main_zsh.profile"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
