---
- name: Install KDE Plasma minimal desktop selection
  community.general.pacman:
    name: "{{ kde_packages }}"
    state: present
  become: yes
  tags: kde

- name: Enable plasma-login-manager (starts on next boot)
  ansible.builtin.systemd:
    name: plasmalogin.service
    enabled: true
  become: true
  tags: kde
