---
- name: Install Python3, pip, and Poetry globally
  community.general.pacman:
    name:
      - python  # Provides python3 on Arch
      - python-pip
      - poetry  # Installs Poetry system-wide
    state: present
    update_cache: true
  become: true
