---

# Switch for packages set
aur_pkg_type: base
aur_pkg:
  base: "{{ aur_basic }}"
  theme: "{{ aur_theme }}"

# Based on https://github.com/Morganamilo/paru#installation
- name: Install base-devel for AUR builds
  become: true
  community.general.pacman:
    name:
      - base-devel
      - git
      - rust
    state: present
  tags: aur-setup

- name: Clone paru AUR helper repository
  ansible.builtin.git:
    repo: https://aur.archlinux.org/paru.git
    dest: /tmp/paru
    depth: 1
  tags: aur-setup

# Create emphemeral passwordless sudo user to by-pass interactive password prompts
 # Issue: makepkg and paru do not allow sudo users, but internally require `sudo pacman` calls...
- name: Create user and install paru and AUR packages
  block:
    - name: Create the `aur_builder` user
      become: true
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel
      tags: aur-setup

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman, /usr/bin/paru"
        create: yes
        mode: 0440
        validate: "visudo -cf %s"
      tags: aur-setup

    - name: Build and install paru
      become_user: aur_builder
      ansible.builtin.shell: |
        set -e
        cd /tmp/paru
        makepkg -si --noconfirm --needed
      args:
        creates: /usr/bin/paru
      tags: aur-setup

    - name: "Install AUR package set: {{ aur_package_set }}"
        become: true
        become_user: aur_builder
        ansible.builtin.command: paru -S --noconfirm --needed {{ item }}
        loop: "{{ aur_packages[aur_package_set] }}"

    # - name: ERROR - test always block
    #   become: true
    #   community.general.pacman:
    #       name:
    #       - gittttttttttttttttttttttt
    #       state: present
    #   tags: aur-setup

  rescue:
    - name: Task fails before clean-up
      ansible.builtin.debug:
        msg: "AUR installation failed. Remove aur_builder user."
      tags: aur-setup

  always:
    - name: Remove temp sudo rule
      become: true
      ansible.builtin.file:
        path: /etc/sudoers.d/11-install-aur_builder
        state: absent
      ignore_errors: yes # in case rule doesnt exist
      tags:
        - aur-setup
        - aur-cleanup

    - name: Remove aur_builder user
      become: true
      ansible.builtin.user:
        name: aur_builder
        state: absent
        remove: yes # rm user home
      ignore_errors: yes # in case user doesnt exist
      tags:
        - aur-setup
        - aur-cleanup
