---
- name: Install zsh and dependencies
  community.general.pacman:
    name:
      - zsh
      - nerd-fonts
    state: present
  become: yes
  tags: zsh

- name: Install starship via curl
  ansible.builtin.shell: |
    curl -sS https://starship.rs/install.sh | sh -s -- --yes
  args:
    creates: /usr/local/bin/starship
  become: yes
  tags: zsh

- name: Add starship to .zshrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['user_dir'] }}/.zshrc"
    block: |
      # Starship prompt
      eval "$(starship init zsh)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Starship"
    create: yes
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: zsh

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /usr/bin/zsh
  become: yes
  tags: zsh
