---
- name: Install ufw
  community.general.pacman:
    name: ufw
    state: present
  become: yes
  tags: firewall

- name: Enable UFW
  ansible.builtin.shell:
    cmd: ufw enable
  become: yes
  tags: firewall

- name: Set default UFW policies
  ansible.builtin.shell:
    cmd: ufw default allow outgoing && ufw default deny incoming
  become: yes
  tags: firewall
