---

# zsh green starship theme
- name: Copy starship configuration
  ansible.builtin.template:
    src: starship.toml.j2
    dest: "{{ ansible_facts['user_dir'] }}/.config/starship.toml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: kde-theme

# Konsole theme
- name: Deploy Konsole configuration
  ansible.builtin.template:
    src: konsolerc.j2
    dest: "{{ ansible_facts['user_dir'] }}/.config/konsolerc"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: kde-theme

- name: Ensure ~/.local/share/konsole exists for profile and colorscheme
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.local/share/konsole"
    state: directory
    mode: '0755'
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
  tags: kde-theme

- name: Deploy Konsole profile
  ansible.builtin.template:
    src: main_zsh.profile.j2
    dest: "{{ ansible_facts['user_dir'] }}/.local/share/konsole/main_zsh.profile"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: kde-theme

- name: Deploy Konsole coloscheme
  ansible.builtin.template:
    src: Sweet-Ambar-Blue.colorscheme.j2
    dest: "{{ ansible_facts['user_dir'] }}/.local/share/konsole/Sweet-Ambar-Blue.colorscheme"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0644'
  tags: kde-theme

# kde
- name: Deploy KDE Plasma config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
    mode: "0644"
    backup: true
  loop:
    - kdeglobals
    - plasmarc
    - plasma-org.kde.plasma.desktop-appletsrc
    - kwinrc
  tags: kde-theme

- name: Deploy wallpaper
  ansible.builtin.copy:
    src: "wallpaper.jpg"
    dest: "{{ ansible_env.HOME }}/.local/share/wallpapers/rasmus-gundorff-saederup-379eC1vAJZA-unsplash.jpg"
    mode: "0644"
  tags: kde-theme

- name: Rebuild KDE sycoca cache
  ansible.builtin.command: kbuildsycoca6
  changed_when: true
  tags: kde-theme
