---

- name: Deploy KDE Plasma config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
    mode: "0644"
    backup: true
  loop:
    - kdeglobals
    - plasmarc
    - plasma-org.kde.plasma.desktop-appletsrc
    - kwinrc

- name: Deploy wallpaper
  ansible.builtin.copy:
    src: "wallpaper.jpg"
    dest: "{{ ansible_env.HOME }}/.local/share/wallpapers/rasmus-gundorff-saederup-379eC1vAJZA-unsplash.jpg"
    mode: "0644"

- name: Rebuild KDE sycoca cache
  ansible.builtin.command: kbuildsycoca6
  changed_when: true
