---
- name: Install docker and docker-compose
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present
    update_cache: true
  become: true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true

- name: Enable and start docker service
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
    state: started
